### ISSUE TITLE
ClassNotFoundException: co.paralleluniverse.fibers.SuspendExecution

### ISSUE THREAD

**Issue by dsabanin** [puniverse/pulsar#20]
I created an empty leiningen project with pulsar, but any attempt to load the REPL or load the environment in any way (there's no code except for lein boilerplate), result in the following exception:

```
$ lein repl
Exception in thread "main" java.lang.NoClassDefFoundError: co/paralleluniverse/fibers/SuspendExecution
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:186)
    at clojure.core_proxy__init.load(Unknown Source)
    at clojure.core_proxy__init.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at clojure.lang.RT.loadClassForName(RT.java:2098)
    at clojure.lang.RT.load(RT.java:430)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core__init.load(Unknown Source)
    at clojure.core__init.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at clojure.lang.RT.loadClassForName(RT.java:2098)
    at clojure.lang.RT.load(RT.java:430)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.lang.RT.doInit(RT.java:447)
    at clojure.lang.RT.<clinit>(RT.java:329)
    at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: co.paralleluniverse.fibers.SuspendExecution
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 22 more
```

Here's more info about my system. The OS is OS X 10.9.2. 

```
$ lein version
Leiningen 2.3.4 on Java 1.7.0_09 Java HotSpot(TM) 64-Bit Server VM

$ java -version
java version "1.7.0_09"
Java(TM) SE Runtime Environment (build 1.7.0_09-b05)
Java HotSpot(TM) 64-Bit Server VM (build 23.5-b02, mixed mode)

$ cat project.clj
(defproject pulsar-text "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
                :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.1"]
                           [co.paralleluniverse/pulsar "0.5.0"]]
  :java-agents [[co.paralleluniverse/quasar-core "0.5.0"]])
```

I tried removing ~/.m2 dir, it didn't help. Tried reproducing it on a Linux system with OpenJDK, but same sample project worked fine. Here's some info about the Linux system (plain Ubuntu VM on DigitalOcean):

```
$ lein version
Leiningen 2.3.4 on Java 1.7.0_55 OpenJDK 64-Bit Server VM

$ uname -a
Linux bs-bench-ny 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

Any ideas?

Thanks!

**Comment by darth10** [comment]
I'm getting the same above error with pulsar/quasar 0.7.2 and Java 1.7.0_21.
The project I'm using is from @yogothos - [https://github.com/yogthos/pulsar-example](https://github.com/yogthos/pulsar-example).

Cloning this project, and running `lein repl` throws the same error.
```
java.lang.NoClassDefFoundError: co/paralleluniverse/fibers/SuspendExecution, compiling:(still.clj:43:9)
```

**Comment by pron** [comment]
Can you share your project file?

**Comment by darth10** [comment]
It's the same one of the project mentioned in the link - [https://github.com/yogthos/pulsar-example/blob/master/project.clj](https://github.com/yogthos/pulsar-example/blob/master/project.clj).
Like I mentioned, I simply cloned the project and ran `lein repl`.

Thanks for your speedy response!

**Comment by darth10** [comment]
Resolved it! Everything seemed working fine after removing the `[refactor-nrepl "1.2.0-SNAPSHOT"]` dependency from my `profiles.cl`j file. 

Thanks again!

**Comment by malchmih** [comment]
Having the same issue as @darth10. I don't think that removing `refactor-nrepl` is a solution, since my primary editor is Emacs and I'd like to keep it :blush: @pron Could you comment on this? clojure-emacs/refactor-nrepl#107 has more info.

**Comment by malchmih** [comment]
I'm sorry, didn't notice #43
