### ISSUE TITLE
Adding pulsar dep breaks refactor-nrepl plugin

### ISSUE THREAD

**Issue by jjcomer** [puniverse/pulsar#43]
When I add pulsar as a dependency (with quasar), the [refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl) plugin is prevented from loading. If I remove pulsar, the plugin starts working again. The [cider-nrepl](https://github.com/clojure-emacs/cider-nrepl) plugin does not have this issue. Not sure where this defect lies, if it is in the plugin or in plusar.

**Comment by circlespainter** [comment]
I don't know much about `refactor-nrepl` but I tried adding the Leiningen plugin to a basically empty project with no deps (specifically no Quasar/Pulsar and no agents) and when I run `lein repl` I get the following:

```
Error loading refactor-nrepl.middleware: java.io.FileNotFoundException: Could not locate cider/nrepl/middleware/util/misc__init.class or cider/nrepl/middleware/util/misc.clj on classpath: , compiling:(refactor_nrepl/middleware.clj:1:1)
Exception in thread "main" java.lang.NoClassDefFoundError: IllegalName: foo.core/run.proxy$java.lang.Object$SignalHandler$d8c00ec7, compiling:(/tmp/form-init8858224983338365557.clj:1:1354)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:957)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$TryExpr$Parser.parse(Compiler.java:2191)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2708)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.eval(Compiler.java:6700)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoClassDefFoundError: IllegalName: foo.core/run.proxy$java.lang.Object$SignalHandler$d8c00ec7
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
	at clojure.core$get_proxy_class.doInvoke(core_proxy.clj:262)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$proxy.doInvoke(core_proxy.clj:335)
	at clojure.lang.RestFn.invoke(RestFn.java:497)
	at clojure.lang.Var.invoke(Var.java:401)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6552)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6630)
	... 41 more
```

Is that the issue you're running into? Else what's the trace/log, if any? How do you know the plugin is prevented from loading? If you can share a testable reproduction of the issue it can greatly help.

**Comment by jjcomer** [comment]
This works with ```lein repl```:
```clojure
(defproject dep-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :plugins [[refactor-nrepl "1.1.0"]])
```

This one breaks with the above error you quote.
```clojure
(defproject dep-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [co.paralleluniverse/pulsar "0.7.2"]]
  :java-agents [[co.paralleluniverse/quasar-core "0.7.2"]]
  :plugins [[refactor-nrepl "1.1.0"]])
```

And to be thorough :wink: this one works too:
```clojure
(defproject dep-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [co.paralleluniverse/pulsar "0.7.2"]]
  :java-agents [[co.paralleluniverse/quasar-core "0.7.2"]])
```

**Comment by jjcomer** [comment]
Also interesting is that both of these work:

```clojure
(defproject dep-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :java-agents [[co.paralleluniverse/quasar-core "0.7.2"]]
  :plugins [[refactor-nrepl "1.1.0"]])
```

```clojure
(defproject dep-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [co.paralleluniverse/pulsar "0.7.2"]]
  :plugins [[refactor-nrepl "1.1.0"]])
```

**Comment by circlespainter** [comment]
Here (Linux Mint 17.2 Rafaela, Oracle JDK 1.8.0_60-b27 64-bit on MBP late 2008) this too breaks with the above error:
```clojure
(defproject dep-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :plugins [[refactor-nrepl "1.1.0"]])
```

**Comment by jjcomer** [comment]
I'm running Ubuntu 15.04 -- Leiningen 2.5.2 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM

Also tried wiping out the my user profile. Turns out you need ```cider-nrepl``` too.

Here is the base then:
```clojure
(defproject dep-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :plugins [[refactor-nrepl "1.1.0"]
            [cider/cider-nrepl "0.9.1"]])
```

**Comment by circlespainter** [comment]
Adding `:bootclasspath true` (which tells Leiningen to add the agent JAR to the boot class path as well) seems to solve the issue, although it's not completely clear why to me; I just don't know enough about those plugins' architecture (or leiningen's plugins classloading architecture for that matter).

This relates to classloading hierarchies anyway, for example `quasar-core` needs be added to the boot class path as well when instrumenting JDK parts; this is because it adds reference to some Quasar runtime classes during instrumentation (which must be loadable by the JDK classloader afterwards).

Does this work for you?

**Comment by beppu** [comment]
@circlespainter Adding `:bootclasspath true` makes the `refactor-nrepl` go away, but then the pulsar code stops working.

I started with https://github.com/yogthos/pulsar-example and edited its `project.clj` to look like:

```clojure
(defproject pulsar-example "0.1.0-SNAPSHOT"
  :description "a sample project using Pulsar"
  :url "https://github.com/yogthos/pulsar-example"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [co.paralleluniverse/pulsar "0.7.3"]
                 [co.paralleluniverse/quasar-core "0.7.3"]]

  :plugins [[refactor-nrepl "1.1.0"]
            [cider/cider-nrepl "0.9.1"]]

  :bootclasspath true

  :manifest {"Premain-Class" "co.paralleluniverse.fibers.instrument.JavaAgent"
             "Agent-Class" "co.paralleluniverse.fibers.instrument.JavaAgent"
             "Can-Retransform-Classes" "true"
             "Can-Redefine-Classes" "true"}

  :java-agents [[co.paralleluniverse/quasar-core "0.7.3"]]

  :main pulsar-example.core
  :uberjar-name "pulsar-example.jar"
  :aot [pulsar-example.core])
```

The REPL loaded just fine, but when I tried to run `(-main)`, it threw a `NullPointerException`.

```
1. Unhandled java.lang.NullPointerException
   (No message)

              ActorLoader.java:  368  co.paralleluniverse.actors.ActorLoader/loadCurrentClass
              ActorLoader.java:  392  co.paralleluniverse.actors.ActorLoader/getCurrentClassFor
              ActorLoader.java:  379  co.paralleluniverse.actors.ActorLoader/getReplacementFor0
              ActorLoader.java:  117  co.paralleluniverse.actors.ActorLoader/getReplacementFor
                    Actor.java:  135  co.paralleluniverse.actors.Actor/checkReplacement
                    Actor.java:  235  co.paralleluniverse.actors.Actor/spawn
                    Actor.java:  203  co.paralleluniverse.actors.Actor/spawn
                      core.clj:   29  pulsar-example.core/-main
                          REPL:    1  pulsar-example.core/eval15500
```

**Comment by beppu** [comment]
### A Workaround

Normally, I have the `refactor-nrepl` and `cider-nrepl` plugins setup in my `~/.lein/profiles.clj`.

To remove `refactor-nrepl`, I create a project-specific `profiles.clj` in the root of the project that overrides `:plugins`:

```clojure
{:user {:plugins ^:replace [[lein-pprint "1.1.1"]
                            [cider/cider-nrepl "0.9.1"]]}}
```

Notice that it doesn't include `refactor-nrepl`.  I can live without that plugin, and at least I have a working REPL with pulsar again.

**Comment by circlespainter** [comment]
@beppu Thanks for posting a workaround. I'll be looking further into this issue.

**Comment by stig** [comment]
Same issue for me with pulsar 0.7.3. @beppu 's work-around works. (I too specify `refactor-nrepl` in ~/.lein/profiles.clj`.)

**Comment by expez** [comment]
@circlespainter the problem you encountered in the second post of this thread is caused by your not specifying a `cider-nrepl` version in your `profiles.clj`.  We assume that dependency is `:provided`, because our plugin works on all versions of that middleware and we didn't want to pollute the classpath unnecessarily by specifying some specific version (and risk overriding the user's preference) when we don't have to.

**Comment by expez** [comment]
here are a few other threads discussing this same issue: 

https://github.com/puniverse/pulsar/issues/20
https://github.com/clojure-emacs/refactor-nrepl/issues/107

**Comment by circlespainter** [comment]
@expez Thanks, it doesn't look like the instrumentation errors in https://github.com/clojure-emacs/refactor-nrepl/issues/107 are the source of the issue because when not using auto-instrumentation I can see no errors in the full instrumentation logs (they can be obtained by adding `:options "vdc"` to the agent entry).

Some tricky interaction with [mranderson](https://github.com/benedekfazekas/mranderson) is possible but it sounds strange that it only happens with `refactor-nrepl` and not with `cider-nrepl`.

This definitely requires some more investigation.

**Comment by malchmih** [comment]
@circlespainter Thanks for your investigation! I would really love to have this solved, since `cider-nrepl + refactor-nrepl` is my main programming environment.

**Comment by greboide** [comment]
does someone has a solution to this, im falling in the same error? also i wasnt able to remove refactor-nrepl as suggested because it is being called by emacs and i dont know how to prevent it from calling automatically, even though it isnt listed in my project.clj file. Any help is appreciated...

**Comment by expez** [comment]
@greboide to get rid of `refactor-nrepl` do `(setq cljr-inject-dependencies-at-jack-in nil)` in your `.emacs`

**Comment by greboide** [comment]
nice, thank you @expez im such a noobie with clojure, i dont think im going to refactor just now, anyway it works like a charm without it!
